language: python
python:
        - "2.7"
        - "3.3"
install:
        - "sudo apt-get -y install libavcodec-dev libavfilter-dev libavformat-dev"
        - "pip install -r requirements.txt"
        - "pip install -r tests/requirements.txt"
script:
        - "python setup.py nosetests"
